name: Build and push docker image
description: Build and push docker image to dockerhub and tag it based on the tag-name(e.g. dev, uat)
inputs:
  tag-name:
    required: true
    type: string
  token:
    description: GitHub token
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      shell: bash

    - name: Get package.json version
      id: package
      run: echo 'version=${{ env.VERSION }}${{ inputs.tag-name == 'dev' && '-dev' || ''  }}-${{ github.sha }}' >> $GITHUB_OUTPUT
      shell: bash

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/gh-react-app:${{ steps.package.outputs.version }}

    - name: Display error message
      if: ${{ failure() }}
      run: |
        echo -e "### Error while building/pushing the app!" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Print output
      run: |
        echo "Deploying..."
        echo "URL => https://${{ inputs.tag-name }}.example.com"
      shell: bash

    - name: Add run summary
      run: echo -e '### Deployed Successfully!\n\nURL => https://${{ inputs.tag-name }}.example.com\nDocker image version => ${{ steps.package.outputs.version }}' >> $GITHUB_STEP_SUMMARY
      shell: bash
