name: Build and push docker image
description: Build and push docker image to dockerhub and tag it based on the tag-name(e.g. dev, uat)
inputs:
  tag-name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      shell: bash
    - name: Get package.json version
      id: package
      run: echo 'VERSION=${{ fromJson(env.PACKAGE_JSON).version }}${{ inputs.tag-name == 'dev' && '-dev' || ''  }}-${{ github.run_attempt }}' >> $GITHUB_OUTPUT
      shell: bash
    - name: Build docker image
      run: docker build -t ${{ env.DOCKER_USERNAME }}/gh-react-app:latest -t ${{ env.DOCKER_USERNAME }}/gh-react-app:${{ steps.package.outputs.VERSION }} .
      shell: bash
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Push imgae to Dockerhub
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/gh-react-app:latest
        docker push ${{ env.DOCKER_USERNAME }}/gh-react-app:${{ steps.package.outputs.VERSION }}
      shell: bash
    - name: Print output
      run: |
        echo "Deploying..."
        echo "URL => https://${{ inputs.tag-name }}.example.com"
      shell: bash
    - name: Add run summary
      run: echo -e '### Deployed Successfully!\n\nURL => https://${{ inputs.tag-name }}.example.com\nDocker image version => ${{ steps.package.outputs.VERSION }}' >> $GITHUB_STEP_SUMMARY
      shell: bash
