name: Lint and unit test
description: installs dependencies, check code quality and run unit tests

runs:
  using: composite
  steps:
    - name: Install dependencies
      id: install-deps
      run: npm install
      shell: bash

    - name: Check lint
      run: npm run lint
      shell: bash

    - name: Unit test
      env:
        CI: true
      run: npm run test
      shell: bash
