name: Pull docker image and deploy
on: [workflow_dispatch]
inputs:
  docker-image-tag:
    type: string
    description: Docker image tag to use for deploying
    required: false
    default: latest
  environment:
    type: choice
    description: Environment to deploy the Docker image
    options:
      - Dev
      - UAT
      - Prod

jobs:
  pull_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get docker image tag and environment info and pull docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/gh-react-app:${{ github.event.inputs.docker-image-tag }}
      - name: Deploy
        run: echo "URL:https://${{ github.event.inputs.environment }} | sed -e 's/\(.*\)/\L\1/'-example.com"
