name: Manual Depoly
on:
  workflow_dispatch:
    inputs:
      docker-image-tag:
        type: string
        description: Docker image tag to use for deploying
        required: false
        default: latest
      environment:
        type: choice
        description: Environment to deploy the Docker image
        options:
          - Dev
          - UAT
          - Prod

jobs:
  pull_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get docker image tag and environment info and pull docker image
        id: docker-pull
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/gh-react-app:${{ github.event.inputs.docker-image-tag }}

      - name: Display error message
        if: ${{ failure() }}
        run: |
          echo -e "### Error while pulling docker image!" >> $GITHUB_STEP_SUMMARY
          exit 0

      - name: Deploy
        shell: bash
        run: |
          echo "Deploying in ${{ github.event.inputs.environment }}..."
          environment_name=$(echo ${{ github.event.inputs.environment }} | tr '[:upper:]' '[:lower:]')
          echo "URL:https://$environment_name.example.com" >> $GITHUB_STEP_SUMMARY
