name: Pull Request
on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize]
jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Check lint
        run: npm run lint
      - name: Unit test
        env:
          CI: true
        run: npm run test
      - name: Build app
        run: npm run build
