name: Pull Request
on:
  pull_request:
    branches:
      [ main, develop, release/tnt-sports-launch ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint and unit test
        uses: ./.github/actions/lint-and-test

      - name: Build app
        uses: docker/build-push-action@v4
