name: Test matrix combos
on:
  pull_request:
    branches:
      - main

env:
  FASTLANE_LANE: "android dev_debugAndroidTV"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create slack message header
        id: message-header
        run: |
          app_name=$(echo ${{ env.FASTLANE_LANE }} | cut -d " " -f 2 | cut -d_ -f 2)
          echo "header=$app_name" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.message-header.outputs.header }}"
