name: Echo Date

on:
  pull_request:
    paths-ignore:
      - "README.md"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "README.md"

jobs:
  echo-date:
    runs-on: ubuntu-latest
    name: "Echo Date"

    steps:
      - name: Run echo date
        run: |
          echo -e "Hello at $(date -I)"
