name: Test matrix combos
on:
  pull_request:
    branches:
      - main

env:
  FASTLANE_LANE: "android dev_debugAndroidTV"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create slack message header
        id: message-header
        run: |
          app_name=$(echo ${{ env.FASTLANE_LANE }} | cut -d " " -f 2 | cut -d_ -f 2)
          echo "header=$app_name" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.message-header.outputs.header }}"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["android", "jio", "xiaomi", "amazon", "aosp"]
        include:
          - platform: "android"
            lane: "debug_devAndroidTv"
            app_name: "app 1"
          - platform: "jio"
            lane: "debug_devJio"
            app_name: "JioTV"
          - platform: "xiaomi"
            lane: "debug_devXiaomiTv"
            app_name: "XiaomiTV"
          - platform: "amazon"
            lane: "debug_devFireTv"
            app_name: "FireTV"
          - platform: "aosp"
            lane: "debug_devAospStbTv"
            app_name: "AOSPTV"
    steps:
      - name: print
        run: echo "${{ matrix.platform }} ${{ matrix.lane }} | ${{ matrix.app_name }}"
