name: UAT release
on:
  push:
    branches:
      - "release/**"
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push docker image
        uses: "./.github/actions/build-docker-image"
        with:
          tag-name: "uat"
